COP-2652: E2E test cases for adding people into sGMR user account
UKHomeOffice/sgmr-service pull request #151
Opened 2020-10-07 12:43 UTC by Bothees

## Description
This Pull Request created for adding e2e test cases for adding people into user account. Test cases includes different scenarios ( both happy & un-happy path).

### How to run the test?
npm run cypress:test -- -- spec cypress/integration/sGMR/add-people.spec.js

## Developer Checklist

\* Required

- [ ] Up-to-date with master branch? \*

- [ ] Does it have tests?

- [ ] Pull request URL linked to JIRA ticket? \*

- [ ] All reviewer comments resolved/answered? \*

Ensure you delete the branch once the Pull Request is merged.

2020-10-08 10:08 UTC, p3dr0migue1 requested changes

2020-10-08 10:08 UTC, p3dr0migue1 commented on cypress/support/utils.js
> +  return Cypress.moment().add(2, 'year').format('DD/MM/YYYY');
This is good, but you could have also have used the faker library they also allow you to add a date in the future and past https://www.npmjs.com/package/faker

2020-10-08 10:09 UTC, p3dr0migue1 commented
The tests are currently failing for me, I'll send you screenshots

2020-10-09 08:58 UTC, Bothees commented on cypress/support/utils.js
> +  return Cypress.moment().add(2, 'year').format('DD/MM/YYYY');
I have checked the faker date generation, It generated Dates with specific format, like "2022-02-09T18:12:15.068Z".
We need the date in format "DD-MM-YYYY" so moment() has the ability to generate dates in any format.

2020-10-09 08:59 UTC, Bothees commented on cypress/integration/sGMR/add-people.spec.js
> +    let errors = ['You must enter a first name',
done.

2020-10-09 09:00 UTC, Bothees commented on cypress/integration/sGMR/add-people.spec.js
> +      people.FirstName = `${people.FirstName}${randomNumber()}`;
Done. Used faker to generate Firstname & Lastname.

2020-10-09 09:00 UTC, Bothees commented on cypress/integration/sGMR/add-people.spec.js
> +    cy.fixture('people.json').then((people) => {
done.

2020-10-09 09:00 UTC, Bothees commented on cypress/integration/sGMR/add-people.spec.js
> +  let PEOPLE;
done.

2020-10-09 09:01 UTC, Bothees commented on cypress/fixtures/people.json
> +  "FirstName": "test",
removed the hardcoded name.

2020-10-12 15:37 UTC, p3dr0migue1 submitted a review, later dismissed

2020-10-12 16:00 UTC, p3dr0migue1 approved these changes

2020-10-12 16:01 UTC, merged