COP-3901: Update tests with new email confirmation work-flow
UKHomeOffice/sgmr-service pull request #215
Opened 2020-12-02 13:58 UTC by Bothees

## Description
This PR has changes to update all e2e tests with the new work-flow for registration through email-confirmation.
Added MailSlurp service to create inbox to receive the confirmation email to extract the token to activate the account. 
Updated Login through API call.
Removed tests related to 2FA.

### How to run the tests?
npm run cypress:test:local

## Developer Checklist

\* Required

- [ ] Up-to-date with master branch? \*

- [ ] Does it have tests?

- [ ] Pull request URL linked to JIRA ticket? \*

- [ ] All reviewer comments resolved/answered? \*

Ensure you delete the branch once the Pull Request is merged.

2020-12-02 16:11 UTC, ajames14 reviewed
LGTM!

2020-12-02 16:12 UTC, ajames14 submitted a review, later dismissed

2020-12-03 16:51 UTC, rafenden requested changes

2020-12-03 16:51 UTC, rafenden commented on cypress/support/commands.js
> +const apiKey = 'e6a3b1f5d1877486bba59baa6800bcccc252997dc7561e56065a0a0d953f75bd';
This should be an env var.

2020-12-03 16:51 UTC, rafenden commented on cypress/support/commands.js
> +          token = /token=([A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*)/.exec(mail.body)[1];
This var could be initialized in the same line
```suggestion
          const token = /token=([A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*)/.exec(mail.body)[1];
```

2020-12-03 16:51 UTC, rafenden commented on cypress/support/commands.js
> +          cy.log('token:', token, 'email', email);
No need to log this.

2020-12-03 16:51 UTC, rafenden commented on cypress/support/commands.js
> +});
I don't see the advantage of creating such functions, instead, I would suggest to use mailslurp package directly.

2020-12-03 16:51 UTC, rafenden commented on package.json
> +        "qs": "^6.9.4",
Please move `qs` package back to the `dependencies` as it's required by the production code.

2020-12-04 11:54 UTC, rafenden commented on cypress/support/commands.js
> +Cypress.Commands.add('createInbox', () => {
This command is never used so please remove it.

2020-12-07 10:00 UTC, ajames14 submitted a review, later dismissed

2020-12-07 10:03 UTC, Bothees commented on cypress/support/commands.js
> +Cypress.Commands.add('createInbox', () => {
Done.

2020-12-07 10:03 UTC, Bothees commented on cypress/support/commands.js
> +const apiKey = 'e6a3b1f5d1877486bba59baa6800bcccc252997dc7561e56065a0a0d953f75bd';
Done

2020-12-07 10:03 UTC, Bothees commented on cypress/support/commands.js
> +          token = /token=([A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*)/.exec(mail.body)[1];
Done.

2020-12-07 12:40 UTC, rafenden requested changes

2020-12-07 12:40 UTC, rafenden commented on cypress/support/commands.js
> +}
We will fetch it the same way on all environments.
```suggestion
const apiKey = Cypress.env('mailSlurpApiKey');
```

2020-12-07 14:53 UTC, rafenden approved these changes

2020-12-07 15:15 UTC, merged