COP-3430 : Add E2E tests for Password reset functionality
UKHomeOffice/sgmr-service pull request #217
Opened 2020-12-07 16:55 UTC by Bothees

## Description
This PR has e2e tests for password reset functionality. 

### How to run the tests ?
npm run cypress:test:local -- --env mailSlurpApiKey=ApiKey --spec cypress/integration/sGMR/password-reset.spec.js

## Developer Checklist

\* Required

- [ ] Up-to-date with master branch? \*

- [ ] Does it have tests?

- [ ] Pull request URL linked to JIRA ticket? \*

- [ ] All reviewer comments resolved/answered? \*

Ensure you delete the branch once the Pull Request is merged.

2020-12-07 17:09 UTC, rafenden requested changes

2020-12-07 17:09 UTC, rafenden commented on package.json
> +        "mailslurp-client": "^8.9.1",
Please move this package to dev dependencies.

2020-12-07 17:09 UTC, rafenden commented on cypress/support/commands.js
> +Cypress.Commands.add('resetPassword', () => {
Please remove this commands, because it's never used.

2020-12-09 17:23 UTC, ajames14 approved these changes

2020-12-10 09:29 UTC, rafenden commented on package-lock.json
> -      "dev": true
Did you change `package-lock.json` manually or it was generated?

2020-12-10 09:31 UTC, Bothees commented on package-lock.json
> -      "dev": true
I ran npm install & it was generated.

2020-12-10 16:16 UTC, rafenden approved these changes

2020-12-10 16:18 UTC, merged