SPCR-110 Add descriptive error summary to People and Vessel tabs
UKHomeOffice/sgmr-service pull request #308
Opened 2022-01-10 16:22 UTC by Adele-B

## Description
Add descriptive error messages to the People and Vessel tab forms. Anchor the error messages to the div surrounding each input.

### To test
- Click on the people tab
- Click on 'save a person'
- Scroll to the bottom and click 'Add to saved people list'
- You should be taken to the error summary at top of page
- Click on the error messages
- They should take you to the top of the relevant inputs

- Repeats steps for the Vessel tab

## Developer Checklist

\* Required

- [x] Up-to-date with master branch? \*

- [ ] Does it have tests?

- [x] Pull request URL linked to JIRA ticket? \*

- [ ] All reviewer comments resolved/answered? \*

Ensure you delete the branch once the Pull Request is merged.

2022-01-10 17:03 UTC, p3dr0migue1 requested changes

2022-01-10 17:03 UTC, p3dr0migue1 commented on src/components/People/FormPerson.jsx
> +      <div id='gender' className={`govuk-form-group ${errors.gender ? 'govuk-form-group--error' : ''}`}>
Double quotes please

2022-01-10 17:03 UTC, p3dr0migue1 commented on src/components/People/FormPerson.jsx
> +      <div id="nationality" className={`govuk-form-group ${errors.nationality ? 'govuk-form-group--error' : ''}`}>
Double quotes on `"govuk-form-group--error"` and everywhere else below

2022-01-10 17:21 UTC, Adele-B commented on src/components/People/FormPerson.jsx
> +      <div id="nationality" className={`govuk-form-group ${errors.nationality ? 'govuk-form-group--error' : ''}`}>
My linter throws an error when I try to put "govuk-form-group--error" in double quotes - is this wrong?
<img width="842" alt="Screenshot 2022-01-10 at 17 19 20" src="https://user-images.githubusercontent.com/72464825/148809585-9285156f-7a6d-4111-91aa-74bc594cc860.png">

2022-01-11 09:11 UTC, jennikate commented on src/components/People/FormPerson.jsx
> +      <div id="nationality" className={`govuk-form-group ${errors.nationality ? 'govuk-form-group--error' : ''}`}>
@Adele-B it should be single quotes for string when it's within JavaScript, and double quotes when it's in html

2022-01-11 09:15 UTC, jennikate commented on src/components/People/FormPerson.jsx
> +      <div id="nationality" className={`govuk-form-group ${errors.nationality ? 'govuk-form-group--error' : ''}`}>
Let me know if your linter isn't supporting this as it's the default rule in the linters we use

2022-01-11 15:47 UTC, jennikate approved these changes
LGTM

2022-01-11 15:50 UTC, merged