Accessibility updates
UKHomeOffice/sgmr-service pull request #407
Opened 2022-03-07 11:48 UTC by jennikate

## Description
Add descriptive links for screen readers to make them accessible until we can update tables more extensively

## To Test
- turn on voice over
- go to manage reports
- tab to voyages
- > Links should read out the vessel, departure date, port, and arrival port
- go to people
- tab to a person
- > Link should read out `edit person firsname lastname`
- go to vessel
- tab to a vessel
- > Link should read out `edit vesselType named vesselName`

## Developer Checklist

\* Required

- [x] Up-to-date with master branch? \*

- [ ] Does it have tests?

- [x] Pull request URL linked to JIRA ticket? \*

- [ ] All reviewer comments resolved/answered? \*

Ensure you delete the branch once the Pull Request is merged.

2022-03-07 14:32 UTC, Adele-B requested changes

2022-03-07 14:32 UTC, Adele-B commented on src/components/ManageReports.jsx
> +                              `Open voyage for ${voyage.vesselName}, departure on ${voyage.departureDate}, dpearture port ${voyage.departurePort}, arrival port ${voyage.arrivalPort}`
The date reads a little odd 2022/02/02, maybe add the formatUIDate function before the departure date, both here and below e.g. `${formatUIDate(voyage.departureDate)}` so the date reads forwards.

2022-03-07 14:32 UTC, Adele-B commented on src/components/ManageReports.jsx
> +                              `Open voyage for ${voyage.vesselName}, departure on ${voyage.departureDate}, dpearture port ${voyage.departurePort}, arrival port ${voyage.arrivalPort}`
Also 'departure' in 'departure port' has a small typo

2022-03-07 15:07 UTC, jennikate commented on src/components/ManageReports.jsx
> +                              `Open voyage for ${voyage.vesselName}, departure on ${voyage.departureDate}, dpearture port ${voyage.departurePort}, arrival port ${voyage.arrivalPort}`
Good catch! Updating that

2022-03-07 15:08 UTC, jennikate commented on src/components/ManageReports.jsx
> +                              `Open voyage for ${voyage.vesselName}, departure on ${voyage.departureDate}, dpearture port ${voyage.departurePort}, arrival port ${voyage.arrivalPort}`
Fixing

2022-03-07 16:54 UTC, Adele-B requested changes

2022-03-07 16:54 UTC, Adele-B commented on src/components/Vessel/VesselTable.jsx
> +                <span id="vesselLabel">{vessel.vesselName}</span>
The voiceover seems to read out the name of the first vessel in the table for each of the checkboxes, rather than the actual vessel name that should relate to the checkboxes

2022-03-14 10:31 UTC, jennikate commented on src/components/Vessel/VesselTable.jsx
> +                <span id="vesselLabel">{vessel.vesselName}</span>
updated to be a label with htmlFor so that it gets read out

2022-03-16 13:25 UTC, closed without merging