V2.2- voyage Plan Tests
UKHomeOffice/sgmr-service pull request #569
Opened 2022-06-01 11:40 UTC by JayanthiiB

### AC / Description of changes

### To Test

### Notes

---

**Remember to merge to feature branches not `master`.**

2022-06-06 15:08 UTC, p3dr0migue1 requested changes

2022-06-06 15:08 UTC, p3dr0migue1 commented on cypress/integration/sGMR/add-people.spec.js
> -        cy.enterPeopleInfo1(people);
Where is `enterPeopleInfo1` coming from? What is replacing it?

2022-06-06 15:08 UTC, p3dr0migue1 commented on cypress/integration/sGMR/add-vessel.spec.js
> +        'You must select if the pleasure craft has an Automatic Identification System (AIS)',
Please mind indentation

2022-06-06 15:08 UTC, p3dr0migue1 commented on cypress/integration/sGMR/add-voyage-report-with-saved-data.spec.js
> +    const numberOfPersons = 2;
Why is this `const` but everything else `let`?

2022-06-06 15:08 UTC, p3dr0migue1 commented on cypress/integration/sGMR/report-form-validation.spec.js
> +        'You must select if the pleasure craft has an Automatic Identification System (AIS)',
Indentation please

2022-06-06 15:08 UTC, p3dr0migue1 commented on cypress/integration/sGMR/report-form-validation.spec.js
> +        'Select if there any prohibited or restricted goods on board',
Please bear in mind indentation

2022-06-06 15:08 UTC, p3dr0migue1 commented on cypress/integration/sGMR/report-form-validation.spec.js
> +    it('Should verify customs details mandatory data',()=>{
There should be a spaces around `() => {`

2022-06-06 15:08 UTC, p3dr0migue1 commented on cypress/support/commands.js
> + // const arrivalToHour = (+arrivalTime[0]+1);
Please remove commented out code, not a good practice when we have version control

2022-06-06 15:08 UTC, p3dr0migue1 commented on cypress/support/commands.js
> +//  cy.get('input[name="arrivalTimeFromHour"]').clear().type(arrivalTime[0]);
Please remove commented out code, not a good practice when we have version control

2022-06-06 15:08 UTC, p3dr0migue1 commented on cypress/support/utils.js
> +  return ['DD/MM/YYYY', 'DD/MM/YYYY HH:mm', 'YYYY-MM-DD','HH:mm'].includes(format)
Please remove commented out code, not a good practice when we have version control

2022-06-06 15:10 UTC, p3dr0migue1 commented
@JayanthiiB my preference would be to close this PR and create two new ones, where you make more than one explicit commit so that its easier for everyone to review. Please have a look at the Viable Data Coding Best Practices for a refresher.

2022-06-07 08:35 UTC, JayanthiiB commented on cypress/integration/sGMR/add-people.spec.js
> -        cy.enterPeopleInfo1(people);
Hi @p3dr0migue1 ,thanks I have changed this in updated test as enterPeopleInfo and enterPeopleTravelDoc than keeping it as enterPeopleInfo and enterPeopleInfo1 in command.js to get values for People page.

2022-06-07 08:35 UTC, JayanthiiB commented on cypress/integration/sGMR/add-vessel.spec.js
> +        'You must select if the pleasure craft has an Automatic Identification System (AIS)',
Thanks , Will be careful.

2022-06-07 08:37 UTC, JayanthiiB commented on cypress/integration/sGMR/report-form-validation.spec.js
> +        'You must select if the pleasure craft has an Automatic Identification System (AIS)',
Sure, thanks

2022-06-07 08:37 UTC, JayanthiiB commented on cypress/integration/sGMR/report-form-validation.spec.js
> +        'Select if there any prohibited or restricted goods on board',
Sure , Thanks

2022-06-07 08:38 UTC, JayanthiiB commented on cypress/integration/sGMR/report-form-validation.spec.js
> +    it('Should verify customs details mandatory data',()=>{
Sure, thanks .Have made the changes.

2022-06-07 08:38 UTC, JayanthiiB commented on cypress/support/commands.js
> +//  cy.get('input[name="arrivalTimeFromHour"]').clear().type(arrivalTime[0]);
Sure, Thanks

2022-06-07 08:58 UTC, closed without merging