Spcr 466
UKHomeOffice/sgmr-service pull request #571
Opened 2022-06-01 14:56 UTC by jennikate

### AC / Description of changes

- create PageContainer to hold layout, ErrorSummary, LoadingSpinner
- add a 500 error handler to getData hook
- update pages to use new PageContainer & 500 error
- - Voyage departure
- - Voyage arrival
- - Voyage people selector
- - Voyage people manifest
- - Voyage employee check (is anyone employed)
- - Voyage employee select (select who is employed)

 

### To Test (Developer)

in the getData hook, change the `.then(() => {})` response to be 
```
.then(() => {
  return ({
    errors: true, status: 500, message: 'There has been a problem please try again later or view the help page', id: 'helpError',
  });
});
```

- view the page
- > the page should show the page level error with help text rather than page data
 _this is the easiest way to see visually what will happen as it is very hard to mock a 500 error to the browser_

- change it back
- run tests
- > there should be a 500 test for each page that has been updated and it should pass

### Notes

**Skipped (reason in bullet)**

- voyage pleasure craft : needs refactor to a single component to make this work properly
- voyage cya : complex page needs thinking

**Not done yet**

- Pleasure craft page
- Pleasure craft form 
- People page
- People form
- Account page
- Account form
- Dashboard
- Manage your voyage reports
- POST/PATCH/DELETE calls

---

**Remember to merge to feature branches not `master`.**

2022-06-07 09:41 UTC, Adele-B requested changes

2022-06-07 09:41 UTC, Adele-B commented on src/pages/voyage/ArrivalForm.jsx
>      setIsLoading(false);
Due to the positioning of the `setIsLoading(false)` here, for some reason, it loads the arrival form with the error message above when the form shouldn't be visible

2022-06-07 09:41 UTC, Adele-B commented on src/pages/voyage/PeopleSelectorForm.jsx
> +    // <div className="govuk-width-container ">
Was this commented out code supposed to be deleted?

2022-06-07 09:41 UTC, Adele-B commented on src/pages/voyage/SkipperDetailsForm.jsx
>      setIsLoading(false);
Due to the positioning of the `setIsLoading(false)` here, the skipper page is doing the same as the arrival page

2022-06-13 08:18 UTC, jennikate commented on src/pages/voyage/PeopleSelectorForm.jsx
> +    // <div className="govuk-width-container ">
Yes! Deleting that :)

2022-06-13 08:33 UTC, jennikate commented on src/pages/voyage/ArrivalForm.jsx
>      setIsLoading(false);
👍

2022-06-13 08:35 UTC, jennikate commented on src/pages/voyage/SkipperDetailsForm.jsx
> +          <div id="responsibleGivenName" className={`govuk-form-group ${errors.responsibleGivenName ? 'govuk-form-group--error' : ''}`}>
👍

2022-06-13 08:35 UTC, jennikate commented on src/pages/voyage/SkipperDetailsForm.jsx
>      setIsLoading(false);
👍

2022-06-13 11:28 UTC, jennikate commented
Splitting into two as need confirmation on whether handling 500's or persisting data is more important as a first step

2022-06-13 11:28 UTC, closed without merging